# Generated by Django 2.2.7 on 2020-01-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='estimated_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(choices=[('meat', (('lamb', 'Lamb'), ('beef', 'Beef'), ('chicken', 'Chicken'))), ('fish', (('salmon', 'Salmon'), ('tuna', 'Tuna'))), ('oil', (('rapeseed', 'Rapeseed'), ('olive', 'Olive'), ('sunflower', 'sunflower')))], default='meat', max_length=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='Write some steps'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('DN', 'Dinner'), ('SP', 'Supper'), ('DR', 'Drink'), ('VG', 'Vegan')], default='BR', max_length=2),
        ),
    ]
